name: test
on: push
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Compile test executable
        run: go build -o testProgram.exe ./testProgram/main.go

      - name: Run tests
        run: go test -v ./...
       